### ISSUE TITLE
Both gtk2 and gtk3?

### ISSUE THREAD

**Issue by fosskers** [yurikoles-aur/minecraft#7]
I was doing some dependency analysis and noticed that `minecraft` requires both varieties of `gtk` as dependencies. Do you happen to know why, is that a blackbox concern from upstream?

**Comment by yurikoles** [comment]
Hi @fosskers,

Honestly, I'm also unsure, I just made maping of deps from [minecraft.deb/control.tar.gz/control](https://git.io/JI67H) file to corresponding ArchLinux packages.

**Comment by fosskers** [comment]
I just rebuilt the package without the `gtk2` dep specified and without it installed at all on my system (so it couldn't link to it secretly) and `minecraft-launcher` just exits immediately with a 255 error code. Doesn't even print anything, strange.

Ok, thanks. So both really are necessary for some reason.
